# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:

  legacy_roles:
    default: false
    description: |
      Request roles instead of extensions
    type: boolean
  sleep_interval:
    default: 0
    description: |
      How many seconds to sleep between writes
    type: int
