# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:

  legacy_roles:
    default: false
    description: |
      Request roles instead of extensions
    type: boolean
  sleep_interval:
    default: 500
    description: |
      How many milliseconds to sleep between writes
      (app will try to write twice per second by default).
    type: int
